### ISSUE TITLE
Enable Discussions

### ISSUE THREAD

**Issue by tim-stephenson** [openwpm/OpenWPM#1013]
Hello, I had a more of a question which did not feel like an Issue. Would the maintainers be open to [Enabling GitHub Discussions](https://docs.github.com/en/discussions/quickstart)?

**Comment by vringar** [comment]
Hey,
generally I'd encourage the use of [our Matrix channel](https://matrix.to/#/#OpenWPM:mozilla.org?via=mozilla.org) as I monitor it pretty closely. However I have also enabled discussions.
