### ISSUE TITLE
npm install should be npm ci in scripts/build-extension.sh

### ISSUE THREAD

**Issue by tim-stephenson** [openwpm/OpenWPM#1023]
scripts/build-extension.sh:
```
#!/bin/bash

# This script builds and installs the
# webextension instrumentation.

set -e

# Make conda available to shell script
eval "$(conda shell.bash hook)"
conda activate openwpm

pushd Extension
npm install
popd

echo "Success: Extension/openwpm.xpi has been built"

```

`npm ci`, installs based on the exact package versions in package-lock.json, whereas `npm install` resolves package versions based on package.json, choosing newest allowed package versions based on sematic versioning rules. Though it is unlikely that the version differences from `npm install` and `npm ci`, would have functional differences, it is best practice that the exact same version is used by users as when developing and testing.

**Comment by englehardt** [comment]
Thanks! I'm curious for @vringar's take.

**Comment by vringar** [comment]
Seems reasonable. I've seen it as a best practice in other places, but didn't make the change yet.
