### ISSUE TITLE
Convert console.log messages in extension to use logging module

### ISSUE THREAD

**Issue by englehardt** [openwpm/OpenWPM#103]
Once #71, #76, and #77 land we will deprecate proxy-based instrumentation due to issues with HTTPS sites, missing non-HTTP cookies, and missing requests/responses for cached resources. When we do so the majority of our instrumentation will be in the extension.

It would be ideal to have a module within the extension to manage logging. Since we already have a log process running via `automation/MPLogger.py`, it should be relatively easy to add in additional handling for logs sent over from the extension via a socket.

**Comment by englehardt** [comment]
Extension logging harness was added by Dillon in #126. We need to convert our current `console.log` logging to use the new harness throughout the extension.

**Comment by vringar** [comment]
@Ayushsunny wanna look around our WebExtension code under `openwpm/Extension` and see if there are any console.log calls left around?

**Comment by Ayushsunny** [comment]
> @Ayushsunny wanna look around our WebExtension code under `openwpm/Extension` and see if there are any console.log calls left around?

@vringar According me there are no any `console.log` calls are left after digging that huge file. what to do next sir ?
