### ISSUE TITLE
 Capture the data leaked by the trackers

### ISSUE THREAD

**Issue by lucasvalcantara** [openwpm/OpenWPM#1035]
Hello, I'm a computer engineering student, and I'm doing a deanonymization job using OpenWPM, I want to make some purchases with bitcoin on sites like bitrefill, capture the data leaked by the trackers, and then compare them on the bitcoin blockchain.
Could anyone give me some idea how to get started, I'm confused by the openWpm documentation. 
Can anyone give me an idea? Which opwnwpm module to use? If I can make this small capture of the data leaked by the trackers with openwpm?
thanks

**Comment by vringar** [comment]
Asking for instructions should happen in Discussions
