### ISSUE TITLE
mamba: error: unrecognized arguments: --force

### ISSUE THREAD

**Issue by AlbertoFDR** [openwpm/OpenWPM#1088]
Running the Docker build I found this issue. I think this could happen for more people and it could be because some changes on `mamba`. For solving the issue, just edit the `install.sh` file and remove the `--force` arg in `line 32` and `line 35`. After saving the file, the build should work.

**Comment by vringar** [comment]
Hey,
Thanks for reporting this.
Do you also have time turn this fix into a PR?

**Comment by AlbertoFDR** [comment]
Yeah no problem, give me 10 minutes :)

**Comment by AlbertoFDR** [comment]
PR done! 
But, please, before accepting the PR, check that it's not just my `setup` issue. 
I have not checked if this problem is for everyone.
