### ISSUE TITLE
Move/add instrumentation tests to automation/Extension/webext-instrumentation

### ISSUE THREAD

**Issue by motin** [openwpm/OpenWPM#330]
These tests should be decoupled from the framework tests.

**Comment by motin** [comment]
To ensure that the tests are decoupled from the framework code, it not only needs its own tests, but also its own way of executing those tests.

Unit tests are already [set up](https://github.com/mozilla/OpenWPM/blob/e08e6c9f9593bd20ce35a834a06642a9bcf1bf44/automation/Extension/webext-instrumentation/package.json#L23), but any test that relies on web extension APIs requires testing using a real browser.

I dug around to find the most up to date best practices for testing web extensions using a real browser, and it seems that proper tooling that supports Web Extension developer workflows is still rare, and such tooling that supports Web Extension that uses Web Extension Experiments outside the Firefox source code tree is even rarer. 

The best practice is, from what I have gathered, is still to use Mocha or similar together for writing functional browser-level tests, as in https://github.com/mozilla/shield-studies-addon-template/tree/master/test/functional

A set of re-usable Selenium test methods (like https://github.com/mozilla/shield-studies-addon-utils/tree/master/testUtils) for high-level browser automation (setting up profiles, starting/restarting the browser, installing web extensions etc) makes writing these tests easier.

I found a way last year [to access the Web Extension background context using Selenium](https://github.com/mozilla/webext-experiment-utils#a-note-on-automatic-testing-of-webextension-experiments), but while it works, it is rather clunky and slow. While it is still the current best practice for add-ons outside the tree, [puppeteer-firefox](https://www.npmjs.com/package/puppeteer-firefox) may soon become a viable alternative, allowing direct access to extension background context (as well as speedier functional tests and a better development experience in general).

I have found no examples of code coverage instrumented that works with Web Extension tests when a real browser is used, but at least https://theintern.io seems to be able to instrument code coverage even when running tests via Selenium so maybe there is some hope...

Measuring impact of add-ons performance is discussed in https://discourse.mozilla.org/t/analyze-add-ons-performance-impact-on-a-user/41813 (presentation of the exthouse add-on from June 27 2019: https://mzl.la/add-ons-demos-2019-06-27)

Taken all of this into account, my intention is to make https://github.com/mozilla/shield-studies-addon-utils/tree/master/testUtils available outside of the study utils package and then set up Selenium-based tests for webext-instrumentation. I'll possibly evaluate puppeteer-firefox and try out theintern.io as well in order to see if the current best practices can be improved upon.

**Comment by vringar** [comment]
I don't think we'll ever separate the instrumentation from OpenWPM ever again.
