### ISSUE TITLE
Scan for third-party GMP storage

### ISSUE THREAD

**Issue by ehsan** [openwpm/OpenWPM#472]
It would be nice to be notified when doing web crawls if there is a third-party attempting to obtain EME storage.  Gecko Media Plugin backends leave their storage in the profile.  Currently you could look at the directories under `$PROFILE_DIR/gmp/$PLATFORM/gmp-widevinecdm/id/` and for each one you'll find two files named `origin` and `topLevelOrigin` there containing the origin information for the page requesting the EME API.

It would be nice to get a report of the cases where these origins did not match when a crawl job was finished by scanning the profile directory.

**Comment by englehardt** [comment]
Doing this check at the end of a crawl would require fixing https://github.com/mozilla/OpenWPM/projects/2. But we could check at the end of each page visit.

A while back I started doing this by [instrumenting several `Media*` APIs](https://github.com/englehardt/OpenWPM/commit/a38b49ba20eb910a05c673ac83c0ba4c912016f3), but had to switch to other things before I was able to dig too deep. Would inspecting the profile give more information than these APIs?
