### ISSUE TITLE
Add an option for JS instrumentation to only capture first 1000 characters of "value"

### ISSUE THREAD

**Issue by birdsarah** [openwpm/OpenWPM#616]
I have found the "value" column of the JS table can get very large which causes huge memory inefficiencies. I always pre-process my data to just get the first 1000 characters and have only ever done analysis on that. We could save data, bandwidth, etc. by having an option to have the extension truncate this value for us.

**Comment by vringar** [comment]
I think this can be done as a post-processing step.
