### ISSUE TITLE
Consider breaking out webdriver_utils into separate package

### ISSUE THREAD

**Issue by birdsarah** [openwpm/OpenWPM#649]
I think we want to go the direction of getting openwpm down to just it's core to make it easier to manage. Stumbled across: https://github.com/mozilla/OpenWPM/blob/master/automation/Commands/utils/webdriver_utils.py and while I can see the usefulness, it seems like this could be separated out.

I also have a nagging feeling that I've seen a package with similar functionality although I can't find it on a quick search (I thought maybe PyPOM). cc ing @davehunt - is there a package that has functionality like that in webdriver_utils or am I misremembering?

**Comment by davehunt** [comment]
> I also have a nagging feeling that I've seen a package with similar functionality although I can't find it on a quick search (I thought maybe PyPOM). cc ing @davehunt - is there a package that has functionality like that in webdriver_utils or am I misremembering?

PyPOM provides some base objects for representing pages and regions. There might be some overlap with `webdriver_utils.py` (perhaps `wait_until_loaded`) but not much else. In my opinion it's probably not worth the effort of splitting these out.
