### ISSUE TITLE
List of failed website visits

### ISSUE THREAD

**Issue by vringar** [openwpm/OpenWPM#655]
For some reason or another all of the following websites got stuck in the redis-queue.
``` 1) "99939,thebalanceeveryday.com"
 2) "96695,toocool2betrue.com"
 3) "94269,vaughn.live"
 4) "44267,gentside.com"
 5) "88315,larepublica.cat"
 6) "82581,ehowenespanol.com"
 7) "81376,49erswebzone.com"
 8) "79271,screencrush.com"
 9) "78548,cftvseginfo.com.br"
10) "71387,xsport.ua"
11) "70400,vilmanunez.com"
12) "69634,pillowtalk.com.au"
13) "65172,pressdemocrat.com"
14) "61600,irishcentral.com"
15) "61252,crooksandliars.com"
16) "59627,vrs.gov.mm"
17) "59790,journalstar.com"
18) "58629,ino.com"
19) "58485,worldofwargraphs.com"
20) "58100,ont.by"
21) "54565,eduwill.net"
22) "54261,tray.io"
23) "53045,eadlaureate.com.br"
24) "49762,vantagefx.com"
25) "48419,richmond.com"
26) "47965,diaridegirona.cat"
27) "44897,sketchful.io"
28) "43405,literarydevices.com"
29) "37863,quickanddirtytips.com"
30) "37798,mogelpower.de"
31) "37090,icd10data.com"
32) "34274,bookvoed.ru"
33) "34112,bcbay.com"
34) "32511,gnadoemagazine.com"
35) "32386,dailyherald.com"
36) "30546,adidas.co.uk"
37) "27957,scarymommy.com"
38) "19018,adidas.ru"
39) "23803,autocarindia.com"
40) "23916,blogfolha.uol.com.br"
41) "23104,tiffany.com"
42) "22538,aboutespanol.com"
43) "22004,curiouscat.me"
44) "20263,calendarr.com"
45) "18612,infoworld.com"
46) "18084,gamebanana.com"
47) "17975,miningpoolstats.stream"
48) "16853,ecowatch.com"
49) "16689,13tv.co.il"
50) "13850,towleroad.com"
51) "13796,blu-ray.com"
52) "12341,lockerdome.com"
53) "11506,sekai-kabuka.com"
54) "10668,realtime-chart.info"
55) "10058,unknowncheats.me"
56) "9461,sanslimitesn.com"
57) "8233,namemc.com"
58) "7722,dhlottery.co.kr"
59) "7587,novelupdates.com"
60) "5792,lepoint.fr"
61) "6456,lequipe.fr"
62) "6123,speedrun.com"
63) "6122,thewindowsclub.com"
64) "5359,em.com.br"
65) "4920,statefarm.com"
66) "4477,hilton.com"
67) "4222,csfd.cz"
68) "3127,walla.co.il"
69) "3321,menshealth.com"
70) "2060,aa.com"
71) "1912,ctvnews.ca"
72) "1423,theatlantic.com"
73) "760,interia.pl"
74) "663,techradar.com"
```
I'll try to go through and find out why they failed but I just wanted to document the failures here.

**Comment by vringar** [comment]
1) "95886,jeepgarage.org"
 2) "95776,goggles4u.com"
 3) "93900,rocketium.com"
 4) "89980,sahmplus.com"
 5) "87785,wheresgeorge.com"
 6) "84941,makinglemonadeblog.com"
 7) "84582,sausageroll.com.au"
 8) "77722,drdavinahseats.com"
 9) "74797,appdividend.com"
10) "74991,680news.com"
11) "74347,clickview.com.au"
12) "73838,overclockers.com"
13) "73294,pics.livejournal.com"
14) "70946,googest.ru"
15) "70408,chelseasmessyapron.com"
16) "68631,wowinterface.com"
17) "67161,northamericanmotoring.com"
18) "67899,rutor-games.info"
19) "63164,fourfourtwo.com"
20) "60796,homesteadandchill.com"
21) "60154,eventhubs.com"
22) "58732,realitytvrevisited.com"
23) "58397,noonacademy.com"
24) "56463,echelonfit.com"
25) "54219,bolde.com"
26) "52854,mundoprimaria.com"
27) "52511,activistpost.com"
28) "51927,mobilefun.co.uk"
29) "51409,thebalanceeveryday.com"
30) "48339,espncdn.com"
31) "48228,strava.cz"
32) "45978,h1g.jp"
33) "45011,multibankfx.com"
34) "42765,goolams.ru"
35) "42674,brit.co"
36) "41079,subaruforester.org"
37) "40330,aboutespanol.com"
38) "39279,houstonchronicle.com"
39) "38477,gbmb.org"
40) "38105,shein.com.hk"
41) "37011,9hits.com"
42) "34876,0352.ua"
43) "759,shein.com"
44) "34397,pleated-jeans.com"
45) "32874,ohnotheydidnt.livejournal.com"
46) "32537,greenme.com.br"
47) "31323,vwvortex.com"
48) "30571,espnf1.com"
49) "30438,shein.co.uk"
50) "30058,elledecor.com"
51) "29472,realtime-chart.info"
52) "28330,avsforum.com"
53) "28422,glclck.ru"
54) "25200,troubleshooter.xyz"
55) "24827,udayavani.com"
56) "24022,lopezdoriga.com"
57) "21658,lanebryant.com"
58) "22089,indiatv.in"
59) "20549,clublexus.com"
60) "21607,pushsquare.com"
61) "18262,digital-photography-school.com"
62) "19202,lockerdome.com"
63) "18452,lawebdelprogramador.com"
64) "18286,gbatemp.net"
65) "15304,selbst.de"
66) "14892,oprahmag.com"
67) "13962,al.com"
68) "13718,autonomous.ai"
69) "12858,vidaextra.com"
70) "10794,cheatcc.com"
71) "12287,majorgeeks.com"
72) "10301,sekai-kabuka.com"
73) "10240,9to5google.com"
74) "8848,mtgazone.com"
75) "6124,imgflip.com"
76) "8120,camelcamelcamel.com"
77) "7937,hsn.com"
78) "7279,itstillworks.com"
79) "5843,tecmint.com"
80) "5490,shein.com.mx"
81) "5221,jbzd.com.pl"
82) "5007,mmo-champion.com"
83) "4201,overwatchleague.com"
84) "3063,alfabank.ru"
85) "1326,linguee.com"
86) "542,livejournal.com"
87) "554,coingecko.com"
88) "355,nike.com"

**Comment by englehardt** [comment]
@vringar can we close this?

**Comment by vringar** [comment]
I think all of these websites crash our crawler repeatedly, so I was hoping, I'd find the time to investigate them and turn these one by one into higher quality issues. 
But if you want, we can close this
