### ISSUE TITLE
Document developing on windows

### ISSUE THREAD

**Issue by birdsarah** [openwpm/OpenWPM#657]
Have tested workflow with #648 branch on WSL1 and 2 and it worked smoothly.

Setting up WSL:
https://docs.microsoft.com/en-us/windows/wsl/install-win10

**Comment by vringar** [comment]
Hm, I still think it's valid to say that people should use Ubuntu.
Whether that Ubuntu is running under WSL2 or a VM is something that researchers can decide for themselves.
