### ISSUE TITLE
Have a test to check if packages need repinning.

### ISSUE THREAD

**Issue by birdsarah** [openwpm/OpenWPM#659]
When #648 merges, it should be easy enough to write a test that we could run on a travis cron job that runs `repin.sh` for us and checks if there are updates. If there are, we would get a test failure, which presumably would land in steve's inbox, but I'm guessing there's a way to open an issue or have some kind of more global notification for the team to act on.

**Comment by englehardt** [comment]
I would prefer a warning over an error. The travis jobs run every so often in a cron job and this would guarantee that we'd eventually start failing that build part way through a release cycle.

**Comment by vringar** [comment]
I'd love to have this but I don't think I'll ever get around to it, so closing.
