### ISSUE TITLE
Revert workaround of manually creating user.js

### ISSUE THREAD

**Issue by boolean5** [openwpm/OpenWPM#867]
PR https://github.com/mozilla/OpenWPM/pull/864 restores support for stateful crawling by using custom browser profiles.

However, geckodriver has a bug that makes it write the browser preferences we set, as well as its own default browser preferences, to a `user.js` file in the wrong profile directory when using a custom profile: https://github.com/mozilla/geckodriver/issues/1844. As a temporary workaround until this issue gets fixed, we create the `user.js` file ourselves.

In order to do this, we keep a [copy](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/configure_firefox.py#L10L67) of geckodriver's default preferences in `configure_firefox.py`. Then, we [combine](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/configure_firefox.py#L70L88) those with existing preferences (if the browser profile already contains a `user.js` file), with [privacy](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/configure_firefox.py#L102L129) and [optimization](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/configure_firefox.py#L132L252) preferences set in `configure_firefox.py` and with [preferences](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/deploy_firefox.py#L148L155) specified in `browser_params.prefs`. Finally, we [write](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/configure_firefox.py#L91L99) preferences in a `user.js` file in the browser profile.

In addition, because geckodriver uses the `user.js` file to let Firefox know which port Marionette should use, our workaround includes [picking](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/deploy_firefox.py#L128L135) a free port, writing it to `user.js` and [passing](https://github.com/mozilla/OpenWPM/blob/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/openwpm/deploy_browsers/deploy_firefox.py#L167L169) it to geckodriver as a command line argument.

Once https://github.com/mozilla/geckodriver/issues/1844 is fixed and the fix is included in a geckodriver release we should revert this workaround and let geckodriver handle the creation of the `user.js` file, as well as the selection of the Marionette port.

The exact commit containing the workaround that we should revert is a355dc8.
Additionally, we should remove from the Release Checklist the [step](https://github.com/mozilla/OpenWPM/blame/bfc4644a717ee2cd9c7e83fee1dd9272d14d6a71/docs/Release-Checklist.md#L14) about updating geckodriver default preferences.

**Comment by vringar** [comment]
Since mozilla/geckodriver#1844 is now fixed, we should remove the workaround now.

**Comment by vringar** [comment]
(Assigning this to myself unless @boolean5 has too much free time over the holidays and wants to revert this themselves :smile: )

**Comment by boolean5** [comment]
Hey @vringar! Thanks for reaching out! I'd be happy to work on this in a couple of days :)

**Comment by vringar** [comment]
Thank you so much!
