### ISSUE TITLE
Shutdown taking forever

### ISSUE THREAD

**Issue by MaazBinMusa** [openwpm/OpenWPM#922]
I created the docker image and in it I am using 30 browser instances. If I crawl 100 sites it completes the crawl and shuts down. However if I move up to 250 or 500 crawls. The crawls complete. I get this message as well:

`storage_controller   - INFO     - Received shutdown signal!`

But it takes hours and still the program does not terminate.

**Comment by vringar** [comment]
Could you check in log file if the storage_controller logs any useful debug messages there?
The logs are always written to in debug mode, so there might be more useful info there.

**Comment by vringar** [comment]
Hopefully fixed by #1057
