### ISSUE TITLE
Privacy Extentions

### ISSUE THREAD

**Issue by MaazBinMusa** [openwpm/OpenWPM#952]
Is there any support of privacy extensions? I used seleniums install_addon and gave it an xpi of UBO. It seemed to load the extension just fine.

However I am unable to change selected filter lists. Previously updating storage.js file would do the trick. However I am unable to go around this problem at the moment.

**Comment by vringar** [comment]
Hey,
Have a look at #941
Basically, you have to install the add-on manually on a preferably fresh profile, then package up that and set it as the seed_profile for your crawl.

**Comment by MaazBinMusa** [comment]
Hey thanks!

I am instead doing this in deploy_firefox.py after webdriver is launched. 

```
for extension in extensions:
        driver.install_addon(os.path.join(root_dir,'uBlock0@raymondhill.net.xpi'), temporary=True)
```

I have an xpi at this directory and it is loading it fine. 

My only concern is if the browser restarts will it load the extension?

**Comment by MaazBinMusa** [comment]
I set reset to true in the execute_command_sequence function and it seems to still load the extension. Not sure where it would not persist otherwise
