### ISSUE TITLE
Custom command sequence for browser fingerprinting analysis?

### ISSUE THREAD

**Issue by ssadhuka** [openwpm/OpenWPM#960]
Hi,

I am trying to use OpenWPM to do some basic browser fingerprinting analysis.  I see that custom_command.py can be used to make custom command sequences for various tasks, such as counting the number of links on a page.  I am wondering if there are examples of similar code for browser fingerprinting analyses, such as canvas fingerprinting detection, perhaps similar to the code in `Extension`. 

In essence, I am trying to create a function of the form is_fingerprinting(url) which:
1. Utilizes OpenWPM's crawlers to search through various JS scripts and objects on a site.
2. Detects instances of browser fingerprinting, for some definition of fingerprinting.  As an initial pass, suppose the webpage is fingerprinting if and only if it collects info on screen size and/or colors/fonts used.

If anyone has some pointers for (2) in particular using OpenWPM, it would be much appreciated!  Sorry, I am new to OpenWPM and fairly new to JavaScript, so any examples would be appreciated!

-Shuvom

**Comment by vringar** [comment]
Hey Shuvom,

I would suggest to not try to detect whether a website is fingerprinting while running the crawl.

Instead I would suggest that you have a look at [the documentation for the JS-Instrument](https://openwpm.readthedocs.io/en/latest/Configuration.html#js-instrument) and collect information on the APIs you care about.

This data will then be saved into the SQLite database (assuming you didn't choose a different storage provider) and you can analyze it after the crawl has completed.

To do this, you can either use raw SQL or have a look at [OpenWPM-utils](https://github.com/mozilla/openwpm-utils) for analysis in python.

**Comment by ssadhuka** [comment]
Thank you, this is very helpful!  Is there an example script for the types of analysis OpenWPM does for fingerprinting detection?  Of course, I can do an analysis for a fairly simple definition, but given OpenWPM's vast database of fingerprinting sites, I was wondering if there's a specific example of a comprehensive analysis done.

**Comment by vringar** [comment]
Unfortunately the fingerprinting detection we did at Mozilla remains secret to avoid trackers gaming our heuristics. 
However, feel free to look through the papers written with OpenWPM and see if they have a definition that matches yours.
Sorry for not having code to show.
