### ISSUE TITLE
demo.py running error

### ISSUE THREAD

**Issue by kyleyoon12** [openwpm/OpenWPM#978]
Hi, I am trying to run demo.py but leaving the below error. Seems like there is no appropriate extension thus I tried to install by running 'build-extension.sh' but failed. Would you mind taking a look at this issue?

For your information, I followed up on your instruction under "installation" and "pre-requisites". I am using a fresh ubuntu-20.04.4 / Linux environment. Thank you in advance.

**[demo.py]**

browser_manager      - INFO     - BROWSER 422774449: Launching browser...
browser_manager      - ERROR    - BROWSER 422774449: Crash in driver, restarting browser manager
Traceback (most recent call last):
  File "/home/kyle/OpenWPM/openwpm/browser_manager.py", line 716, in run
    driver, browser_profile_path, display = deploy_firefox.deploy_firefox(
  File "/home/kyle/OpenWPM/openwpm/deploy_browsers/deploy_firefox.py", line 152, in deploy_firefox
    driver.install_addon(ext_loc, temporary=True)
  File "/home/kyle/anaconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/firefox/webdriver.py", line 267, in install_addon
    return self.execute("INSTALL_ADDON", payload)["value"]
  File "/home/kyle/anaconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "/home/kyle/anaconda3/envs/openwpm/lib/python3.9/site-packages/selenium/webdriver/remote/errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: No such file or directory: /home/kyle/OpenWPM/Extension/firefox/openwpm.xpi

browser_manager      - ERROR    - BROWSER 422774449: Spawn unsuccessful  | Profile Created: True  | Profile Tar: True  | Display: True  | Launch Attempted: True  | Browser Launched: False  | Browser Ready: False 

**[build-extension.sh]**

~/OpenWPM/Extension/firefox ~/OpenWPM/scripts
./build-extension.sh: line 13: npm: command not found
~/OpenWPM/Extension/webext-instrumentation ~/OpenWPM/Extension/firefox ~/OpenWPM/scripts
./build-extension.sh: line 15: npm: command not found
~/OpenWPM/Extension/firefox ~/OpenWPM/scripts
./build-extension.sh: line 17: npm: command not found
~/OpenWPM/scripts
Success: Extension/firefox/openwpm.xpi has been built

**Comment by kyleyoon12** [comment]
I needed to install node.js by running "apt-get install -y npm". Later on, I could run "build-extension.sh" successfully. Then I ran demo.py and now I am facing "FileNotFoundError: [Errno 2] No such file or directory: '/tmp/firefox_profile_vtm6bz_7/extension_port.txt'" error. I'll see what I can do to solve it.

**Comment by wesley-tan** [comment]
How did you solve the issue @kyleyoon12
