### ISSUE TITLE
Tracking javascript events

### ISSUE THREAD

**Issue by shashigharti** [openwpm/OpenWPM#987]
Hi,

I am trying to use openwpm to track user activities (js events). But I could not log/get js button click and other events. Does web-extension(js instrumentation) track the data such as button click and other other events ?

**Comment by vringar** [comment]
Hmm, I don't really know. I wrote some ideas in the [openwpm matrix channel](https://matrix.to/#/!pFJihVSEWzcMCcOzSH:mozilla.org/$UxpDQB95Ok_cMtsdq-CzU0vkhrTWksZSVXRJXr0hrhg?via=mozilla.org&via=matrix.org&via=lounge.wtf) so maybe that helps.

Another thing that comes to mind is instrumenting the event you want to capture.
Does adding `"SubmitEvent"` or `"MouseEvent"` to the `js_instrument_settings` work? Or is that what you tried?

**Comment by shashigharti** [comment]
Thank you very much. I am trying to integrate openwpm webext-instrumentation for a webextension app. I want to track all js events so I am trying to use the js instrumentation for this. I have logged all the instrumentation data but it does not track js clicked and other js events. It logs 'javascript_cookies' data only. This is  my config settings, I also added js_instrument_setting:
```
 let config = {
    navigation_instrument: true,
    cookie_instrument: true,
    js_instrument: true,
    js_instrument_settings:["SubmitEvent", "MouseEvent"],
    cleaned_js_instrument_settings: [
      {
        object: `window.CanvasRenderingContext2D.prototype`,
        instrumentedName: "CanvasRenderingContext2D",
        logSettings: {
          propertiesToInstrument: [],
          nonExistingPropertiesToInstrument: [],
          excludedProperties: [],
          logCallStack: false,
          logFunctionsAsStrings: false,
          logFunctionGets: false,
          preventSets: false,
          recursive: false,
          depth: 5,
        },
      },
    ],
    http_instrument: true,
    callstack_instrument: true,
    save_content: false,
    testing: true,
    browser_id: 0,
  };
```

**Comment by vringar** [comment]
Hey, please use the browser_params in python code to configure the JS Instrument. Otherwise you'd have to learn the full syntax for cleanes_js_instrument_settings, which does not seem like a good use of time.

Add the `["SubmitEvent", "MouseEvent"]` to the `browser_params` here:
https://github.com/openwpm/OpenWPM/blob/65c284b99f657e0c26fd42a0b82228303d2ce2de/demo.py#L22-L37

**Comment by shashigharti** [comment]
Thank you!
