### ISSUE TITLE
crawler recursion depth

### ISSUE THREAD

**Issue by sal123-droid** [openwpm/OpenWPM#991]
Hey,
I want to configure the crawler recursion depth from the demo.py file, but I can't find the right command to control it.
anyone knows how can I change or control it?
thanks

**Comment by englehardt** [comment]
Because of the way OpenWPM is architected we don't have proper spidering support. The closest you'll see is https://github.com/openwpm/OpenWPM/blob/master/openwpm/commands/browser_commands.py#L164 which is a depth of 1 beyond the initial page.
